#!/usr/bin/env python3
"""Run the repository's Mask R-CNN on the flat dataset and export COCO JSON.

The input files are expected to use the following naming convention::

    episode_000000_step_00001_modality_rgb_id_0.npy
Only RGB files are read. Instances, classes and masks are generated by
Detectron2 inference instead of being loaded from the saved ``bbs``/``bbsgt``
modalities.
"""

import argparse
import json
import re
from pathlib import Path

import numpy as np


DEFAULT_DATASET = Path(
    "/home/wpp/Look_Around_And_Learn/exps/policies/"
    "08-03-19-40-12_policy_habitat_gibson_randomgoals.yaml_None/dataset"
)
DEFAULT_OUTPUT = Path(
    "third_parties/detectron2/datasets/embodied_disagree3/annotations/instances_train.json"
)
DEFAULT_CONFIG = Path(
    "third_parties/detectron2/configs/embodied/mask_rcnn_R_50_FPN_1x_embodied.yaml"
)
DEFAULT_MODEL = Path("third_parties/detectron2/models/model_final_a54504.pkl")

# Contiguous category ids used by the exported embodied COCO dataset.
CLASS_NAMES = {
    0: "chair",
    1: "couch",
    2: "bed",
    3: "toilet",
    4: "refrigerator",
}
# The bundled model_final_a54504.pkl has an 80-class COCO head. Detectron2's
# class ids are zero-based contiguous COCO ids (chair=56, ..., refrigerator=72).
MODEL_CLASS_TO_CATEGORY = {56: 0, 57: 1, 59: 2, 61: 3, 72: 4}

RGB_PATTERN = re.compile(
    r"^episode_(?P<episode>\d+)_step_(?P<step>\d+)_modality_rgb_id_(?P<camera>\d+)\.npy$"
)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-dir", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--output-json", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument(
        "--score-thresh", type=float, default=0.5, help="Mask R-CNN score threshold"
    )
    parser.add_argument(
        "--device",
        default=None,
        help="inference device, e.g. cuda, cuda:0 or cpu (default: auto)",
    )
    parser.add_argument(
        "--image-dir",
        type=Path,
        default=DEFAULT_DATASET+"_images",
        help="PNG output directory (default: <output dataset root>/images)",
    )
    parser.add_argument(
        "--include-empty",
        action="store_true",
        help="also emit images for which Mask R-CNN predicts no instances",
    )
    parser.add_argument("--save-position", action="store_true")
    parser.add_argument(
        "--limit", type=int, default=None, help="process only the first N RGB frames"
    )
    return parser.parse_args()


def modality_path(dataset_dir, episode, step, modality, camera):
    return dataset_dir / (
        f"episode_{episode:06d}_step_{step:05d}_modality_{modality}_id_{camera}.npy"
    )


def mask_to_rle(binary_mask):
    from pycocotools import mask as mask_utils

    rle = mask_utils.encode(np.asfortranarray(binary_mask.astype(np.uint8)))
    rle["counts"] = rle["counts"].decode("utf-8")
    return rle


def build_predictor(config_path, model_path, score_thresh, device):
    import torch
    from detectron2.config import get_cfg
    from detectron2.engine import DefaultPredictor

    if not 0.0 <= score_thresh <= 1.0:
        raise ValueError("--score-thresh must be between 0 and 1")
    if not config_path.is_file():
        raise FileNotFoundError(f"Mask R-CNN config does not exist: {config_path}")
    if not model_path.is_file():
        raise FileNotFoundError(f"Mask R-CNN weights do not exist: {model_path}")

    cfg = get_cfg()
    # Custom keys used by this repository's embodied config/PruneRCNN.
    cfg.VIS = False
    cfg.SAVE_PTH = ""
    cfg.DATASET_NAME = ""
    cfg.MODEL.NUM_CLASSES = 80
    cfg.merge_from_file(str(config_path))
    cfg.MODEL.WEIGHTS = str(model_path)
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = score_thresh
    cfg.MODEL.DEVICE = device or ("cuda" if torch.cuda.is_available() else "cpu")
    cfg.freeze()
    return DefaultPredictor(cfg), cfg.MODEL.DEVICE


def tensor_numpy(value):
    if hasattr(value, "tensor"):
        value = value.tensor
    if hasattr(value, "detach"):
        value = value.detach().cpu().numpy()
    return np.asarray(value)


def convert(args):
    import cv2

    dataset_dir = args.dataset_dir.expanduser().resolve()
    if not dataset_dir.is_dir():
        raise FileNotFoundError(f"dataset directory does not exist: {dataset_dir}")

    config_path = args.config.expanduser().resolve()
    model_path = args.model.expanduser().resolve()
    predictor, device = build_predictor(
        config_path, model_path, args.score_thresh, args.device
    )

    # Keep generated files in the COCO dataset root. The source dataset may be
    # a read-only symlink to another disk, so writing next to it is unreliable.
    image_dir = args.image_dir or args.output_json.parent.parent / "images"
    image_dir.mkdir(parents=True, exist_ok=True)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)

    frames = []
    for rgb_path in dataset_dir.glob("episode_*_step_*_modality_rgb_id_*.npy"):
        match = RGB_PATTERN.match(rgb_path.name)
        if match:
            frames.append(tuple(map(int, match.group("episode", "step", "camera"))))
    frames.sort()
    if args.limit is not None:
        frames = frames[: args.limit]

    coco = {
        "info": {},
        "images": [],
        "categories": [
            {"id": class_id, "name": class_name}
            for class_id, class_name in CLASS_NAMES.items()
        ],
        "annotations": [],
    }

    annotation_id = 0
    skipped_empty = 0
    invalid_classes = 0
    print(
        f"running Mask R-CNN on {len(frames)} RGB frames "
        f"(device={device}, score_thresh={args.score_thresh})"
    )
    for frame_index, (episode, step, camera) in enumerate(frames, start=1):
        rgb_path = modality_path(dataset_dir, episode, step, "rgb", camera)
        rgb = np.load(rgb_path, allow_pickle=False)
        if rgb.ndim != 3 or rgb.shape[2] < 3:
            raise ValueError(f"unexpected RGB shape {rgb.shape}: {rgb_path}")
        height, width = rgb.shape[:2]
        # Habitat stores RGB, while DefaultPredictor expects an OpenCV BGR image.
        bgr = cv2.cvtColor(rgb[:, :, :3], cv2.COLOR_RGB2BGR)
        instances = predictor(bgr)["instances"].to("cpu")
        classes = tensor_numpy(instances.pred_classes).astype(np.int64)
        keep = np.asarray(
            [int(class_id) in MODEL_CLASS_TO_CATEGORY for class_id in classes],
            dtype=bool,
        )
        invalid_classes += int((~keep).sum())
        if len(instances):
            instances = instances[keep]

        if len(instances) == 0 and not args.include_empty:
            skipped_empty += 1
            if frame_index % 100 == 0 or frame_index == len(frames):
                print(f"processed {frame_index}/{len(frames)} frames")
            continue

        image_id = len(coco["images"])
        image_name = f"epi{episode}_camera{camera}_step{step}.png"
        if not cv2.imwrite(str(image_dir / image_name), bgr):
            raise OSError(f"failed to write image: {image_dir / image_name}")

        image_info = {
            "id": image_id,
            "file_name": image_name,
            "width": int(width),
            "height": int(height),
        }
        if args.save_position:
            position_path = modality_path(dataset_dir, episode, step, "position", camera)
            position = np.load(position_path, allow_pickle=True).item()
            image_info["position"] = np.asarray(position["position"]).tolist()
            orientation = position["orientation"]
            if hasattr(orientation, "components"):
                orientation = orientation.components
            image_info["rotation"] = np.asarray(orientation).tolist()
        coco["images"].append(image_info)

        if len(instances) == 0:
            continue
        classes = tensor_numpy(instances.pred_classes).astype(np.int64)
        boxes_xyxy = tensor_numpy(instances.pred_boxes)
        masks = tensor_numpy(instances.pred_masks)
        if masks.ndim == 4 and masks.shape[1] == 1:
            masks = masks[:, 0]

        for class_id, box, mask in zip(classes, boxes_xyxy, masks):
            x1, y1, x2, y2 = map(float, box)
            binary_mask = np.asarray(mask, dtype=bool)
            coco["annotations"].append(
                {
                    "id": annotation_id,
                    "image_id": image_id,
                    "category_id": MODEL_CLASS_TO_CATEGORY[int(class_id)],
                    "segmentation": mask_to_rle(binary_mask),
                    "area": int(binary_mask.sum()),
                    # COCO JSON requires XYWH, unlike Detectron2's internal XYXY.
                    "bbox": [x1, y1, x2 - x1, y2 - y1],
                    "iscrowd": 0,
                    "episode_step_camera": [episode, step, camera],
                }
            )
            annotation_id += 1

        if frame_index % 100 == 0 or frame_index == len(frames):
            print(f"processed {frame_index}/{len(frames)} frames")

    with args.output_json.open("w", encoding="utf-8") as file:
        json.dump(coco, file)

    print(
        f"saved {len(coco['images'])} images and {len(coco['annotations'])} annotations "
        f"to {args.output_json} (empty: {skipped_empty}, invalid classes: {invalid_classes})"
    )


if __name__ == "__main__":
    convert(parse_args())
