_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "PruneRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]    # 大于第二个值，筛选前景
    SCORE_THRESH_TEST: 0.5
DATASETS:
  TRAIN: ("proj_train",)
  TEST: ("proj_train",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)     
  MAX_ITER: 5     #90000   # 

VIS: True
