defaults:
  - detectron_args: maskrcnn
  - training: pipeline_gt #pipeline_semantic
  - hydra: default

notes: vsqf_v1_3
exp_name: ${now:%m-%d-%H-%M-%S}_${training.exp_name_training}_consensus_${training.consensus}_bs_${training.batch_size}_notes_${notes}

# data
sample_path:  /home/users/wpp/Semantic-Curiosity/Semantic-Curiosity/exps/dump/vsqf_v1_3_eval/episodes_data
# /home/users/wpp/Semantic-Curiosity/Semantic-Curiosity/exps/dump/vsqf_v3_1_eval/episodes_data
# /home/users/wpp/Semantic-Curiosity/Semantic-Curiosity/exps/dump/random4vsqf/episodes_data
# /home/users/wpp/Semantic-Curiosity/Semantic-Curiosity/exps/dump/vsqf_v1_eval_re/episodes_data

# test mode
testset_path: /home/wpp/Seman-Curiosity/data/vsqf_test_val5/data
test_mode: all   # all / uncertainty
test_uncertain_func: 2  # 0: margin 1: cls entropy 2: seg entropy
test_budget: 3000
uncertain_pth: /home/wpp/Seman-Curiosity/data/vsqf_test_val5/uncertainty_sum_cam.pkl

# training params
update_target: True   # TODO
n_iterations: 1
checkpoint_path: 
# /home/wpp/Seman-Curiosity/exps_finetune/2025-12-02/12-02-15-15-48_gt_consensus_vanilla_bs_8_notes_vsqfcam_v2_rand_re/iteration-0.ckpt
# /home/wpp/Seman-Curiosity/exps_finetune/2025-12-02/12-02-11-35-43_gt_consensus_vanilla_bs_8_notes_vsqfcam_v2/iteration-0.ckpt
# vsqfcam v2 
# /home/wpp/Seman-Curiosity/exps_finetune/2025-12-02/12-02-11-35-43_gt_consensus_vanilla_bs_8_notes_vsqfcam_v2/iteration-0.ckpt

# random
# /home/wpp/Seman-Curiosity/exps_finetune/2025-11-26/11-26-21-43-34_gt_consensus_vanilla_bs_8_notes_vsqf_active1_rand_all/iteration-0.ckpt

# vsqf + activecam
# /home/wpp/Seman-Curiosity/exps_finetune/2025-11-26/11-26-14-54-13_gt_consensus_vanilla_bs_8_notes_vsqf_active1_test2k/iteration-0.ckpt

# vsqf
# /home/wpp/Seman-Curiosity/exps_finetune/2025-11-24/11-24-11-59-49_gt_consensus_vanilla_bs_8_notes_vsqf_active1/iteration-0.ckpt

# vsqf_rand
# /home/wpp/Seman-Curiosity/exps_finetune/2025-11-24/11-24-15-37-55_gt_consensus_vanilla_bs_8_notes_vsqf_active1_random/iteration-0.ckpt


# training device
gpus: [2,]   # 指定gpu: [1,2,3] 多gpu训练  

base_dir: /home/wpp/Seman-Curiosity/




