ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True 
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SENSORS: ['GPS_SENSOR', 'COMPASS_SENSOR', 'OBJECT_DETECTOR_GT_SENSOR', 'AGENT_POSITION_SENSOR',]
  OBJECT_DETECTOR_GT_SENSOR:
    TYPE: object_detector_gt
  AGENT_POSITION_SENSOR:
    TYPE: position_sensor
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: "data2/datasets/objectnav/gibson/v3/{split}/{split}.json.gz"
  EPISODES_DIR: "data2/datasets/objectnav/gibson/v3/{split}/"
  # DATA_PATH: "data/datasets/objectnav/gibson/v3/{split}/{split}.json.gz"
  # EPISODES_DIR: "data/datasets/objectnav/gibson/v3/{split}/"
  SCENES_DIR: "data2/scene_datasets/"
  CONTENT_SCENES: [
  # [
  #   "Allensville.glb", 
  #   "Beechwood.glb", "Coffeen.glb", "Cosmos.glb", "Forkland.glb",
  #   "Hanson.glb", "Hiteman.glb", "Klickitat.glb", "Lakeville.glb", "Leonardo.glb", 
  #   "Lindenwood.glb", "Marstons.glb", "Merom.glb", "Mifflinburg.glb", "Newfields.glb",
  #   "Onaga.glb", "Pinesdale.glb", "Pomaria.glb", "Ranchester.glb", "Shelbyville.glb",
  #   "Stockman.glb", "Tolstoy.glb", "Wainscott.glb", "Woodbine.glb" 
  # ]
    # "Collierville",
    # "Corozal",
    # "Darden",
    # "Markleeville.glb",
  # ]
  "Airport.glb"
  ]
# 