_BASE_: "../Base-RCNN-FPN.yaml"
AdverTrain: True
MODEL:
  META_ARCHITECTURE: AdverRCNN
  WEIGHTS: "/home/users/wpp/Look_Around_And_Learn/third_parties/detectron2/output/7/model_0004999.pth"
  # "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: AdverROIHeads
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_clsag_train_seen',)   # name of dataset
  TEST: ('voc_clsag_val_seen','voc_clsag_val_unseen',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100

VIS: False
OUTPUT_DIR: "./output/7/"
OUTPUT_VISDIR: "vis_pred/"